### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by willer-lu** [BlackHalo-Drake/SAGNN-Substructure-Aware-Graph-Neural-Networks#1]
It's wonderful work.
I ran into a bug while reproducing the code, and I didn't find a solution for it. Anyone else has encountered this problem while reproducing the changed code or can the author help?
```
Traceback (most recent call last):
  File "/home/lugewei/anaconda3/envs/lgw/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/lugewei/anaconda3/envs/lgw/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/lugewei/.virtualenvs/untitled2/SAGNN/train/zinc.py", line 100, in <module>
    run(cfg, create_dataset, create_model, train, test)
  File "/home/lugewei/.virtualenvs/untitled2/SAGNN/core/train_helper.py", line 124, in run
    train_dataset, val_dataset, test_dataset = create_dataset(cfg)
  File "/home/lugewei/.virtualenvs/untitled2/SAGNN/train/zinc.py", line 37, in create_dataset
    calculate_stats(train_dataset)
  File "/home/lugewei/.virtualenvs/untitled2/SAGNN/core/utils.py", line 4, in calculate_stats
    ave_num_nodes = np.array([g.num_nodes for g in dataset]).mean()
  File "/home/lugewei/.virtualenvs/untitled2/SAGNN/core/utils.py", line 4, in <listcomp>
    ave_num_nodes = np.array([g.num_nodes for g in dataset]).mean()
AttributeError: 'collections.defaultdict' object has no attribute 'num_nodes'
```

**Comment by BlackHalo-Drake** [comment]
You can try to reinstall the running environment. Generally, such errors are caused by the packages of the running environment conflicting with each other.

**Comment by willer-lu** [comment]
Actually,it’s the second time I ran into this bug,I have built a new environment ,or could you offer specific version of all packages?

**Comment by BlackHalo-Drake** [comment]
I have checked the code and setting num workers to 0 should solve the problem.

**Comment by willer-lu** [comment]
Thank you for your quick reply,but the num_workers in core/config.py is 0 originally.

**Comment by LWL-cpu** [comment]
Actually, this problem is due to the mismatch of num_workers between processing data and runing training process. You can process and save the data before running the program training again, and there will be no problem. We are very sorry that this is an issue with our early work. We will optimize our code in the future!
